import type { Metadata } from "next";
import { Geist, Geist_Mono, Heebo, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "./Component/Footer";
import Header from "./Component/Header/page";
import ScrollToTop from "./Component/ScrollToTop";
import PageHeader from "./Component/PageHeader";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Load Heebo and Inter through next/font/google
const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["latin"],
  weight: ["800"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kider - Pre School Website",
  description: "Generated by create next app",
  icons: {
    icon: "logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Retained FontAwesome stylesheet; Google Fonts link removed */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${heebo.variable} ${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Providers>
          <Suspense fallback={<div>Loading...</div>}>
            <ScrollToTop />
            <Header />
            <PageHeader title="Kider - Pre School Website" />
            {children}
          </Suspense>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}