import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "./component/footer";
import Header from "./component/header/page";
import ScrollToTop from "./component/scrolltotop";
import PageHeader from "./component/pageheader";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kider - Pre School Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@800&family=Inter:wght@400;600;700&display=swap" rel="stylesheet"></link>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        
        <Providers>
          {/* 2. Wrap components that might use useSearchParams in Suspense */}
          <Suspense fallback={<div>Loading...</div>}>
            <ScrollToTop />
            <Header />
            <PageHeader title="Kider - Pre School Website" />
            {children}
          </Suspense>
        </Providers>
        <Footer />
       
      </body>
    </html>
  );
}
